extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:prettier/recommended
rules:
    react/react-in-jsx-scope: off
    react/jsx-uses-react: off
    prettier/prettier:
        - error
        - endOfLine: auto
    react/prop-types: off
    no-unused-vars:
        - warn
        - argsIgnorePattern: ^_
          varsIgnorePattern: ^_

