extends:
    - eslint:recommended
    - plugin:react/recommended
    - plugin:prettier/recommended
env:
    browser: true
    node: true
parserOptions:
    ecmaVersion: latest
    sourceType: module
    ecmaFeatures:
        jsx: true
rules:
    react/react-in-jsx-scope: off
    react/jsx-uses-react: off
    prettier/prettier:
        - error
        - endOfLine: auto
    react/prop-types: off
    no-unused-vars:
        - warn
        - argsIgnorePattern: ^_
          varsIgnorePattern: ^_

